spring:
  application:
    name: testing-api

fabric:
  channel-name: "mychannel"
  chaincode-name: "basic"
  mspId: "Org1MSP"
  peer-endpoint: "localhost:7051"
  override-auth: "peer0.org1.example.com"

server:
  port: 9090
